#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.1_AR73068 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Aug 05 12:19:39 PDT 2022
# SW Build 2580384 on Sat Jun 29 08:04:45 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -prj rfnoc_block_difi_tb_vlog.prj"
xvlog --incr --relax -prj rfnoc_block_difi_tb_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj rfnoc_block_difi_tb_vhdl.prj"
xvhdl --incr --relax -prj rfnoc_block_difi_tb_vhdl.prj 2>&1 | tee -a compile.log

