#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.1_AR73068 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Aug 05 12:19:41 PDT 2022
# SW Build 2580384 on Sat Jun 29 08:04:45 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 5d0508c4f05d4dd7b17af2651b87dade --incr --debug all --relax --mt 8 -d "UHD_FPGA_DIR=/home/spectrum/chdr_difi/rfnoc-difi/uhddev/fpga/usrp3/top/../.." -d "WORKING_DIR="/home/spectrum/chdr_difi/rfnoc-difi/oot_rfnoc_difi/fpga/rfnoc_block_difi"" -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_15 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot rfnoc_block_difi_tb_behav xil_defaultlib.rfnoc_block_difi_tb xil_defaultlib.glbl -log elaborate.log -timescale 1ns/1ns"
xelab -wto 5d0508c4f05d4dd7b17af2651b87dade --incr --debug all --relax --mt 8 -d "UHD_FPGA_DIR=/home/spectrum/chdr_difi/rfnoc-difi/uhddev/fpga/usrp3/top/../.." -d "WORKING_DIR="/home/spectrum/chdr_difi/rfnoc-difi/oot_rfnoc_difi/fpga/rfnoc_block_difi"" -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_15 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot rfnoc_block_difi_tb_behav xil_defaultlib.rfnoc_block_difi_tb xil_defaultlib.glbl -log elaborate.log -timescale 1ns/1ns

