#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.1_AR73068 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Aug 05 12:19:53 PDT 2022
# SW Build 2580384 on Sat Jun 29 08:04:45 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim rfnoc_block_difi_tb_behav -key {Behavioral:sim_1:Functional:rfnoc_block_difi_tb} -tclbatch rfnoc_block_difi_tb.tcl -log simulate.log"
xsim rfnoc_block_difi_tb_behav -key {Behavioral:sim_1:Functional:rfnoc_block_difi_tb} -tclbatch rfnoc_block_difi_tb.tcl -log simulate.log

